# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envadress',
            name='env_num',
            field=models.CharField(max_length=20, verbose_name='环境地址编号'),
        ),
    ]
