# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattaryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间戳')),
                ('battary_num', models.CharField(max_length=20, unique=True, verbose_name='电池编号')),
                ('soc', models.FloatField(blank=True, null=True, verbose_name='电池剩余电量')),
            ],
        ),
        migrations.CreateModel(
            name='BattatyProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated_capacity', models.FloatField(blank=True, null=True, verbose_name='电池额定电量')),
            ],
        ),
        migrations.CreateModel(
            name='LoadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间戳')),
                ('load_num', models.CharField(max_length=20, unique=True, verbose_name='负载编号')),
                ('load_p', models.FloatField(blank=True, null=True, verbose_name='有功功率')),
                ('load_q', models.FloatField(blank=True, null=True, verbose_name='无功功率')),
            ],
            options={
                'verbose_name': '负载值',
                'verbose_name_plural': '负载值',
            },
        ),
        migrations.AlterField(
            model_name='devcontrol',
            name='dev_type',
            field=models.IntegerField(choices=[(1, '光伏组逆变器'), (2, '光伏板'), (3, '风力逆变器'), (4, '风机'), (5, '燃料电池逆变器'), (6, '燃料电池'), (11, '蓄电池组逆变器'), (12, '蓄电池'), (13, '飞轮逆变器'), (14, '飞轮'), (20, '高压负荷开关'), (21, '隔离开关'), (22, '断路器'), (30, '负载')], verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='webmicrogrid',
            name='area_type',
            field=models.IntegerField(choices=[(0, '间隔区'), (1, '光伏区'), (2, '风力区'), (3, '燃机区'), (4, '电池储能区'), (5, '飞轮储能区'), (6, '负载区'), (7, '控制区'), (8, '环境')], verbose_name='区域类别'),
        ),
    ]
