# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0002_auto_20180423_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvAdress',
        ),
        migrations.AlterField(
            model_name='webmicrogrid',
            name='area_name',
            field=models.IntegerField(blank=True, choices=[(0, '总区'), (1, '光伏区'), (2, '风力区'), (3, '电池储能区'), (4, '控制区'), (5, '环境')], null=True, verbose_name='区域类别'),
        ),
    ]
