# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0003_auto_20180423_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_num', models.CharField(max_length=20, verbose_name='环境地址编号')),
                ('env_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址名')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '环境监测地址',
                'verbose_name_plural': '环境监测地址',
            },
        ),
        migrations.AlterField(
            model_name='webmicrogrid',
            name='area_name',
            field=models.IntegerField(blank=True, choices=[(0, '总区'), (1, '光伏区'), (2, '风力区'), (3, '电池储能区'), (4, '控制区')], null=True, verbose_name='区域类别'),
        ),
    ]
