# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0005_auto_20180423_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devcontrol',
            name='dev_type',
            field=models.IntegerField(choices=[(1, '光伏组逆变器'), (2, '蓄电池组逆变器'), (2, '高压负荷开关'), (3, '隔离开关'), (4, '熔断器')], verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='webmicrogrid',
            name='TYPE',
            field=models.IntegerField(choices=[(1, '区域'), (2, '设备组'), (3, '具体发电设备')], verbose_name='编号类型'),
        ),
        migrations.AlterField(
            model_name='webmicrogrid',
            name='area_name',
            field=models.IntegerField(blank=True, choices=[(0, '间隔区'), (1, '光伏区'), (2, '风力区'), (3, '燃机区'), (3, '电池储能区'), (4, '控制区'), (5, '环境')], null=True, verbose_name='区域类别'),
        ),
        migrations.AlterField(
            model_name='webmicrogrid',
            name='parent_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='microgrids.WebMicrogrid', to_field='num', verbose_name='设备所属区'),
        ),
    ]
