# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0006_auto_20180424_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webmicrogrid',
            name='area_name',
        ),
        migrations.AddField(
            model_name='webmicrogrid',
            name='area_type',
            field=models.IntegerField(blank=True, choices=[(0, '间隔区'), (1, '光伏区'), (2, '风力区'), (3, '燃机区'), (4, '电池储能区'), (5, '飞轮储能区'), (6, '控制区'), (7, '环境')], null=True, verbose_name='区域类别'),
        ),
    ]
