# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0007_auto_20180424_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webmicrogrid',
            name='TYPE',
        ),
        migrations.AddField(
            model_name='webmicrogrid',
            name='type',
            field=models.IntegerField(choices=[(1, '子区域'), (2, '设备组'), (3, '具体发电设备')], default=1, verbose_name='编号类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devcontrol',
            name='dev_type',
            field=models.IntegerField(choices=[(1, '光伏组逆变器'), (2, '光伏板'), (3, '蓄电池组逆变器'), (4, '蓄电池'), (5, '高压负荷开关'), (6, '隔离开关'), (7, '熔断器')], verbose_name='设备类型'),
        ),
    ]
