# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0009_auto_20180424_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmicrogrid',
            name='control_belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub2', to='microgrids.WebMicrogrid', to_field='num', verbose_name='控制区域所属'),
        ),
        migrations.AlterField(
            model_name='webmicrogrid',
            name='parent_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='microgrids.WebMicrogrid', to_field='num', verbose_name='设备所属区'),
        ),
    ]
