# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0011_auto_20180424_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.AlterField(
            model_name='devcontrol',
            name='dev_type',
            field=models.IntegerField(choices=[(1, '光伏组逆变器'), (2, '光伏板'), (3, '蓄电池组逆变器'), (4, '蓄电池'), (5, '高压负荷开关'), (6, '隔离开关'), (7, '断路器')], verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='webmicrogrid',
            name='parent_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='microgrids.WebMicrogrid', to_field='num', verbose_name='设备上级'),
        ),
    ]
