# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0012_auto_20180425_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img',
            options={'verbose_name': '图片管理', 'verbose_name_plural': '图片管理'},
        ),
        migrations.AddField(
            model_name='img',
            name='name_h',
            field=models.CharField(default='', max_length=30, verbose_name='汉语名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='img', verbose_name='图片'),
        ),
    ]
