# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0013_auto_20180425_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devcontrol',
            name='switch_status',
            field=models.IntegerField(blank=True, choices=[(1, '断开'), (2, '闭合')], default=1, null=True, verbose_name='开关状态控制'),
        ),
    ]
