# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0014_auto_20180427_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentdata',
            name='env_num',
            field=models.CharField(max_length=20, verbose_name='环境地址编号'),
        ),
        migrations.AlterField(
            model_name='pvanalogquantitydata',
            name='pv_num',
            field=models.CharField(max_length=20, verbose_name='光伏逆变器编号'),
        ),
        migrations.AlterField(
            model_name='pvdigitalquantitydata',
            name='pv_num',
            field=models.CharField(max_length=20, verbose_name='光伏逆变器编号'),
        ),
    ]
