# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0016_auto_20180511_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvdigitalquantitydata',
            name='pv_num',
            field=models.CharField(max_length=20, unique=True, verbose_name='光伏逆变器编号'),
        ),
    ]
