# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0017_auto_20180511_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVAnalogQuantityData1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='时间戳')),
                ('pv_num', models.CharField(max_length=20, verbose_name='光伏逆变器编号')),
                ('matrix_cur', models.FloatField(blank=True, null=True, verbose_name='阵列电流')),
                ('matrix_volt', models.FloatField(blank=True, null=True, verbose_name='阵列电压')),
                ('grid_volt_ab', models.FloatField(blank=True, null=True, verbose_name='电网AB线电压')),
                ('grid_volt_bc', models.FloatField(blank=True, null=True, verbose_name='电网BC线电压')),
                ('grid_volt_ca', models.FloatField(blank=True, null=True, verbose_name='电网CA线电压')),
                ('on_grid_cur_a', models.FloatField(blank=True, null=True, verbose_name='A相并网电流')),
                ('on_grid_cur_b', models.FloatField(blank=True, null=True, verbose_name='B相并网电流')),
                ('on_grid_cur_c', models.FloatField(blank=True, null=True, verbose_name='C相并网电流')),
                ('power_factor_a', models.FloatField(blank=True, null=True, verbose_name='A相功率因素')),
                ('power_factor_b', models.FloatField(blank=True, null=True, verbose_name='B相功率因素')),
                ('power_factor_c', models.FloatField(blank=True, null=True, verbose_name='C相功率因素')),
                ('grid_freq', models.FloatField(blank=True, null=True, verbose_name='电网频率')),
            ],
            options={
                'verbose_name': '光伏逆变器模拟量数据1',
                'verbose_name_plural': '光伏逆变器模拟量数据1',
            },
        ),
        migrations.CreateModel(
            name='PVAnalogQuantityData2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='时间戳')),
                ('pv_num', models.CharField(max_length=20, verbose_name='光伏逆变器编号')),
                ('matrix_power_in', models.FloatField(blank=True, null=True, verbose_name='阵列输入功率')),
                ('on_grid_p', models.FloatField(blank=True, null=True, verbose_name='并网有功功率')),
                ('on_grid_q', models.FloatField(blank=True, null=True, verbose_name='并网无功功率')),
                ('on_grid_s', models.FloatField(blank=True, null=True, verbose_name='并网视在功率')),
                ('inv_cabin_temp', models.FloatField(blank=True, null=True, verbose_name='机柜温度')),
                ('day_gen_power', models.FloatField(blank=True, null=True, verbose_name='日累计发电量')),
                ('day_runtime', models.FloatField(blank=True, null=True, verbose_name='日运行时间')),
                ('total_gen_power', models.FloatField(blank=True, null=True, verbose_name='总累计发电量')),
                ('total_runtime', models.FloatField(blank=True, null=True, verbose_name='总运行时间')),
                ('co2_reduce', models.FloatField(blank=True, null=True, verbose_name='CO2减排量')),
            ],
            options={
                'verbose_name': '光伏逆变器模拟量数据2',
                'verbose_name_plural': '光伏逆变器模拟量数据2',
            },
        ),
        migrations.DeleteModel(
            name='PVAnalogQuantityData',
        ),
    ]
