# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microgrids', '0018_auto_20180516_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pvdigitalquantitydata',
            old_name='locking_slef',
            new_name='locking_self',
        ),
    ]
